#  Name the experiment. This name will be the name of the report
experiment_name: "tb3_test"


#Save directory of results
results_directory: "/home/khaled/riout_ws/src/ROSNavBench/results"


#  Add the absolute path of the world
world_path: "/home/khaled/riout_ws/src/ROSNavBench/simulations/worlds/turtlebot3_house_gz.sdf"

#  Add the absolute path of the map
map_path: "/opt/ros/jazzy/share/turtlebot3_navigation2/map/map.yaml"

#  Add the absolute path of the map
map_png_path: "/opt/ros/jazzy/share/turtlebot3_navigation2/map/map.pgm"

#  Add gazebo model path, if multiple path, please spereate them by a :
models_path: "/home/khaled/riout_ws/src/ROSNavBench/simulations"
#  Choose a type of global local planners to be tested
planner_type: ["GridBased"]
#, "smac_planner", "ThetaStar", "Lattice", "SmacHybraid"
#  Choose one of the following controllers, by adding its name to the controller type list
#  Note that these are the avaible controllers for the provided example
#  DWB
#  RPP
#  RPP_RSC
#  DWB_RSC
controller_type: ["DWB", "DWB_RSC", "RPP", "RPP_RSC"] #name of behaviour tree

#  This option is intended for testing the same controller and planner combination several times
#  Min value is one
instances_num: 1

#  Add the absolute path of the robot navigation configuration
nav_config: "/home/khaled/riout_ws/src/ROSNavBench/example/turtlebot3/nav2_config/waffle_pi2.yaml"

#  Add the directory of the behaviour tree
behaviour_tree_directory: "/home/khaled/riout_ws/src/ROSNavBench/example/turtlebot3/behavior_trees"

#  Add the absolute path of the urdf and model files inside single qoutes ''
urdf_file: "/home/khaled/riout_ws/src/ROSNavBench/simulations/urdf/turtlebot3_waffle_pi.urdf"

#  If the robot is spawned by only urdf, then set the model_file to 'None'
model_file: 'None'
#Citeria for performace analysis includes: "Time" ,"CPU", "Memory", "Path Length" , "Safety"
criteria: ["Time", "path_length", "CPU", "Memory", "Safety"]

#Wieght for each criteria as a number from 1 to 9
#Set None if the wieght to be set automatcally giving that the importance to the eariler criteria in the matrix
weights: "None"

trajectory_type: "user_defined" # Options: "user_defined", "auto_generated"

user_defined_trajectories:
  - type: "single_goal"
    spawn_pose:
      x: -2.0
      y: -0.5
      yaw: 0.0
    single_goal:
      x: 1.87151
      y: 0.506992
      theta: 0.4019
